[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
pin = true

[tools]
"aqua:anthropics/claude-code" = "2.1.272"
"aqua:astral-sh/uv" = "0.12.13"
"aqua:cli/cli" = "2.100.0"
"aqua:hugo" = "0.166.0"
"aqua:jdx/usage" = "6.9.1"
"aqua:jq" = "1.8.2"
"npm:@github/copilot" = "1.0.83"
"npm:@openai/codex" = "0.153.4"
"npm:@playwright/cli" = "0.1.19"
"npm:ccusage" = "20.0.20"
"npm:rulesync" = "16.24.1"
"npm:wrangler" = "4.129.1"
"vfox:mise-plugins/vfox-gcloud" = "571.0.0"
deno = "2.9.6"
java = "openjdk-25"
node = "24.21.0"
